### ISSUE TITLE
Ender Portal texture appears randomly

### ISSUE THREAD

**Issue by Lunaccordion** [Poudingue/Vanilla-Normals-Renewed-1.12#10]
When i use it with SEUS renewed, some ender portal textures appears in the stairs/planks...
![2019-06-04_16 05 52](https://user-images.githubusercontent.com/50422710/58885624-d7a29c80-86e2-11e9-9f30-f75d527e41d9.png)
![Uploading 2019-06-04_16.05.54.png…]()

**Comment by Poudingue** [comment]
In surface option, set up texture resolution correctly (x16), it should fix this problem.
