### ISSUE TITLE
blocks bug in 1.12.2

### ISSUE THREAD

**Issue by spartaninconnu83** [Poudingue/Vanilla-Normals-Renewed-1.12#2]
i don't know if the version of minecraft i use is compatible with your texture pack, but i have a bug.
i'm using the "SEUS renewed 1.0.0" and optifine 1.12.2_HD_U_D3" (the optifine is in the mod folder because i use some mods). i don't have any problem with the reflection of metals (screenshots)
![2019-04-17_10 34 22](https://user-images.githubusercontent.com/49712758/56273476-106bbf80-60fd-11e9-9ac7-0b98820da243.png)
![2019-04-17_10 34 09](https://user-images.githubusercontent.com/49712758/56273474-106bbf80-60fd-11e9-8fc4-5995293fcd17.png)

But i have a problem with the 3d of blocks like this:
![2019-04-17_10 35 05](https://user-images.githubusercontent.com/49712758/56273607-57f24b80-60fd-11e9-810e-f246c4e55e0d.png)
(i have an exemple of the texture pack with no problem with that block :https://youtu.be/CIqTp1mEud4?t=209)
 and my second problem is with the 3d of other blocks, like that :
![2019-04-17_10 34 52](https://user-images.githubusercontent.com/49712758/56273682-81ab7280-60fd-11e9-94eb-2c9160c84e8b.png)
![2019-04-17_10 34 40](https://user-images.githubusercontent.com/49712758/56273684-81ab7280-60fd-11e9-8ad5-d4737dcc6893.png)
i know the 3d of blocks are not real, this is just the 3d texture map ect..., But i don't know why the guy in the vidéo (previously linked) have not this block problem.

that's all i think, so i hope you answer me, and have some idea for help me
have a nice day.

**Comment by Poudingue** [comment]
It's because the shader is not set up properly for POM (parallax occlusion mapping).
In the shaders settings -> Surface options, set texture resolution to 16.
