### ISSUE TITLE
Won't appear

### ISSUE THREAD

**Issue by Namecool** [Poudingue/Vanilla-Normals-Renewed-1.12#3]
i've put the file in the right place but the resource pack won't appear in the minecraft 'avaleble resourses' is this my fault or an issue for everybody?

**Comment by MeloriTensei** [comment]
Make sure the asset folder is the first folder u see in the zip file.  If not, extract it and re-zip it yourself.  It'll eventually show up.
EDIT & UPDATE: Just extracting would do
<img width="524" alt="Capture" src="https://user-images.githubusercontent.com/3746534/56754675-34479900-67c0-11e9-8648-ab358a3e1290.PNG">

**Comment by Poudingue** [comment]
Yes, this is because of the way github creates the zip, you can't use it as it is. I don't think there's any way to correct that.

**Comment by Cymmy** [comment]
I am having the same problem that Namecool had. I rezipped my file as you said. Assets is the first folder you see in the new zip but it also was the first in the original zip. It still does not show up in my resources. I also have the extracted file in there. Nothing is working. I have used several other resource files and never had this problem.
