### ISSUE TITLE
Iron Blocks have stripy lines when using SEUS PTGI E6

### ISSUE THREAD

**Issue by MeloriTensei** [Poudingue/Vanilla-Normals-Renewed-1.12#4]
I only used it for the first hour and saw this.  Is this just me or is this the current issue?
I'm using Java JRE 8 Update 212 64-bit version to run it.
I'm using Optifine 1.12.2 HD U E3 with SEUS PTGI E6 with the 5 settings Sonic Ether required to set:
(Copied from Sonic Ether's Patreon post)
OptiFine 1.12.2 HD U E2 or newer
Options > Video Settings > Details > Alternate Blocks: OFF
Options > Video Settings > Details > Trees: Fancy or Fast (Smart may break lighting)
Options > Video Settings > Quality > Natural Textures: OFF
Options > Video Settings > Shaders > Shadow Quality: 1x
Options > Video Settings > Shaders > Old Lighting : DEFAULT

All the other settings are default out of the box.

Hardware details (not sure if needed):
Ryzen 2700X (no iGPU)
ASUS Nvidia GTX 1080 A8G (no OC)
32GB DDR4 OC 3000Mhz RAM (12GB Allocated)
Samsung 970 EVO 1TB SSD
Windows 10 Pro Build 1809 (Cumulative update 04-2019)

Screenshot for your reference:
![2019-04-26_01 12 45](https://user-images.githubusercontent.com/3746534/56754918-c64fa180-67c0-11e9-8c09-58f288916af5.png)

**Comment by MeloriTensei** [comment]
UPDATE: I've discovered that the iron_block_s.png file is the main culprit because as soon as I used Photoshop to edit from
this (current): 
![iron_block_s](https://user-images.githubusercontent.com/3746534/56756603-b46ffd80-67c4-11e9-9db1-24214cd2cb51.png)
to this (my own edit): 
![iron_block_s](https://user-images.githubusercontent.com/3746534/56756629-c2258300-67c4-11e9-821d-9e4f4e8f9052.png)

I got this: 
![2019-04-26_01 44 56](https://user-images.githubusercontent.com/3746534/56756704-f305b800-67c4-11e9-9102-e37c6bb49805.png)

**Comment by Poudingue** [comment]
You can correct this by toggling “Full Raytrace Reflections” in raytracing options.
This is due to the shader not raytracing anything below a certain glossiness value, but in my opinion for metals it should always raytrace regardless of smoothness, because metals are 100% reflective.

**Comment by Poudingue** [comment]
I thought about changing that, but it means making the blocks too smooth for my taste.

**Comment by MeloriTensei** [comment]
Thx for the response.  And it's resolved.  Thx :)
