### ISSUE TITLE
Can you please make a 1.13/1.14 version

### ISSUE THREAD

**Issue by ThatOneCalculator** [Poudingue/Vanilla-Normals-Renewed-1.12#5]
Thanks :)

**Comment by Poudingue** [comment]
I'll do that once SEUS PTGI E7, which should be compatible with 1.13, is out.
If you really want it now, there are existing automatic converters :
https://flodriblog.blogspot.com/2019/04/a-minecraft-resource-pack-convertor.html
https://github.com/icrdr/Resource-Pack-Converter

**Comment by Poudingue** [comment]
The 1.13+ version is now available here : https://github.com/Poudingue/Vanilla-Normals-Renewed-1.13
