### ISSUE TITLE
PTGI e6 only having one bounce of light, but should have more...

### ISSUE THREAD

**Issue by Scapsters** [Poudingue/Vanilla-Normals-Renewed-1.12#6]
In the reflection, you can see the iron blocks, but not their reflection which should be of some red blocks. Is this a problem with my settings? Which ones might it be? Or is it the pack. I've also changed the iron blocks to get rid of the white lines, which someone else had a problem with.
![image](https://user-images.githubusercontent.com/50056819/56853920-7bd33f80-68fc-11e9-88b4-7eb16bb9aeda.png)

Edits: oh my god  print screen is not cooperating and taking screenshots of many seconds ago.

**Comment by Poudingue** [comment]
SEUS only supports one bounce of reflection at the moment, i have no control over it, i only made the resourcepack.
