### ISSUE TITLE
Texture pack not active

### ISSUE THREAD

**Issue by raphlopes** [Poudingue/Vanilla-Normals-Renewed-1.12#7]
I putted the folder in the ressource pack folder, minecraft actually sees it, i can select it on the active texture pack but it does nothing. I got the vanilla textures. I don't know where the problem comes from, one friend tried too and got the same problem.
I'm using also shaders and my friend isn't, but i don't know if this relevant.

**Comment by Poudingue** [comment]
This texturepack is based on the vanilla textures, so without any shader supporting PBR you won't see much change, the base color is almost not changed, i only added normals and specular.
