### ISSUE TITLE
Redstone block is not working.

### ISSUE THREAD

**Issue by Ethan2121** [Poudingue/Vanilla-Normals-Renewed-1.12#9]
With SEUS PTGI E6 the redstone block does not seem to fully glow. Please help.
![2019-05-11_19 10 38](https://user-images.githubusercontent.com/43227286/57576950-254c2200-7421-11e9-8d4b-04f1a538d7c0.png)

**Comment by Poudingue** [comment]
This is because SEUS PTGI E6 doesn't allow emissive metal blocks. With the current version of the resourcepack, i reverted to dielectric for the redstone block, so it should be working now.
